apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperboy-api
  namespace: paperboy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: paperboy-api
  template:
    metadata:
      labels:
        app: paperboy-api
    spec:
      containers:
      - name: api
        image: paperboy:latest
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_URL
          value: "redis://redis:6379/0"
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: paperboy-secrets
              key: supabase-url
        - name: SUPABASE_KEY
          valueFrom:
            secretKeyRef:
              name: paperboy-secrets
              key: supabase-key
        envFrom:
        - configMapRef:
            name: paperboy-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: paperboy-api
  namespace: paperboy
spec:
  selector:
    app: paperboy-api
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer 