#!/usr/bin/env python3
"""
Pattern Matching for OSINT Article Tagging System
Regex patterns to identify specific events, capabilities, and activities
Enhanced with comprehensive China-focused patterns
"""

PATTERNS = [
    # Military Events
    (r"live[- ]?fire (drill|exercise)", "event", "Live Fire Drill"),
    (r"airspace (violation|incursion|breach)", "event", "Airspace Violation"),
    (r"missile (launch|test|fire|firing)", "event", "Missile Launch"),
    (r"military (exercise|drill|maneuver)", "event", "Military Exercise"),
    (r"naval (patrol|exercise|drill)", "event", "Naval Patrol"),
    (r"air defense (exercise|drill)", "event", "Air Defense Exercise"),
    (r"joint (exercise|drill|operation)", "event", "Joint Exercise"),
    (r"freedom of navigation", "event", "Freedom of Navigation"),
    (r"port (visit|call)", "event", "Port Visit"),
    (r"diplomatic (protest|complaint)", "event", "Diplomatic Protest"),
    
    # China-Specific Military Events
    (r"eastern theater command", "actor", "Eastern Theater Command"),
    (r"southern theater command", "actor", "Southern Theater Command"),
    (r"western theater command", "actor", "Western Theater Command"),
    (r"northern theater command", "actor", "Northern Theater Command"),
    (r"central theater command", "actor", "Central Theater Command"),
    (r"people's liberation army", "actor", "People's Liberation Army"),
    (r"pla (navy|air force|army|rocket force)", "actor", "PLA Navy"),
    (r"combat readiness patrol", "event", "Combat Readiness Patrol"),
    (r"joint sea (exercise|drill)", "event", "Joint Sea Exercise"),
    (r"peace mission (exercise|drill)", "event", "Peace Mission Exercise"),
    (r"military parade", "event", "Military Parade"),
    (r"weapons test", "event", "Weapons Test"),
    (r"nuclear test", "event", "Nuclear Test"),
    (r"space launch", "event", "Space Launch"),
    (r"satellite deployment", "event", "Satellite Deployment"),
    
    # Chinese Leadership
    (r"xi jinping", "command", "Xi Jinping"),
    (r"li qiang", "command", "Li Qiang"),
    (r"zhao leji", "command", "Zhao Leji"),
    (r"wang huning", "command", "Wang Huning"),
    (r"cai qi", "command", "Cai Qi"),
    (r"ding xuexiang", "command", "Ding Xuexiang"),
    (r"li xi", "command", "Li Xi"),
    (r"han zheng", "command", "Han Zheng"),
    (r"qin gang", "command", "Qin Gang"),
    (r"wang yi", "command", "Wang Yi"),
    (r"zhang youxia", "command", "Zhang Youxia"),
    (r"he weidong", "command", "He Weidong"),
    (r"liu zhenli", "command", "Liu Zhenli"),
    (r"dong jun", "command", "Dong Jun"),
    (r"wei fenghe", "command", "Wei Fenghe"),
    
    # Chinese Military Units
    (r"74th group army", "unit", "74th Group Army"),
    (r"75th group army", "unit", "75th Group Army"),
    (r"76th group army", "unit", "76th Group Army"),
    (r"77th group army", "unit", "77th Group Army"),
    (r"78th group army", "unit", "78th Group Army"),
    (r"79th group army", "unit", "79th Group Army"),
    (r"80th group army", "unit", "80th Group Army"),
    (r"81st group army", "unit", "81st Group Army"),
    (r"82nd group army", "unit", "82nd Group Army"),
    (r"83rd group army", "unit", "83rd Group Army"),
    (r"north sea fleet", "unit", "North Sea Fleet"),
    (r"east sea fleet", "unit", "East Sea Fleet"),
    (r"south sea fleet", "unit", "South Sea Fleet"),
    (r"rocket force", "unit", "PLA Rocket Force"),
    (r"strategic support force", "unit", "PLA Strategic Support Force"),
    (r"people's armed police", "actor", "People's Armed Police"),
    (r"china coast guard", "actor", "China Coast Guard"),
    (r"maritime militia", "actor", "Maritime Militia"),
    (r"fishing militia", "actor", "Fishing Militia"),
    
    # Chinese Military Platforms
    (r"j-20", "platform", "J-20"),
    (r"j-16", "platform", "J-16"),
    (r"j-15", "platform", "J-15"),
    (r"j-10", "platform", "J-10"),
    (r"j-35", "platform", "J-35"),
    (r"j-31", "platform", "J-31"),
    (r"h-6", "platform", "H-6"),
    (r"h-20", "platform", "H-20"),
    (r"y-20", "platform", "Y-20"),
    (r"z-20", "platform", "Z-20"),
    (r"z-10", "platform", "Z-10"),
    (r"type 055", "platform", "Type 055"),
    (r"type 052d", "platform", "Type 052D"),
    (r"type 054a", "platform", "Type 054A"),
    (r"type 075", "platform", "Type 075"),
    (r"type 003", "platform", "Type 003"),
    (r"liaoning", "platform", "CV-16 Liaoning"),
    (r"shandong", "platform", "CV-17 Shandong"),
    (r"fujian", "platform", "CV-18 Fujian"),
    (r"df-21", "platform", "DF-21"),
    (r"df-26", "platform", "DF-26"),
    (r"df-17", "platform", "DF-17"),
    (r"df-31", "platform", "DF-31"),
    (r"df-41", "platform", "DF-41"),
    (r"yj-18", "platform", "YJ-18"),
    (r"yj-12", "platform", "YJ-12"),
    (r"hq-9", "platform", "HQ-9"),
    (r"hq-16", "platform", "HQ-16"),
    
    # Chinese Cities and Provinces
    (r"beijing", "geo", "Beijing"),
    (r"shanghai", "geo", "Shanghai"),
    (r"guangzhou", "geo", "Guangzhou"),
    (r"shenzhen", "geo", "Shenzhen"),
    (r"chongqing", "geo", "Chongqing"),
    (r"tianjin", "geo", "Tianjin"),
    (r"wuhan", "geo", "Wuhan"),
    (r"nanjing", "geo", "Nanjing"),
    (r"hangzhou", "geo", "Hangzhou"),
    (r"chengdu", "geo", "Chengdu"),
    (r"xi'an", "geo", "Xi'an"),
    (r"qingdao", "geo", "Qingdao"),
    (r"dalian", "geo", "Dalian"),
    (r"guangdong", "geo", "Guangdong"),
    (r"jiangsu", "geo", "Jiangsu"),
    (r"shandong", "geo", "Shandong"),
    (r"zhejiang", "geo", "Zhejiang"),
    (r"sichuan", "geo", "Sichuan"),
    (r"hubei", "geo", "Hubei"),
    (r"hunan", "geo", "Hunan"),
    (r"xinjiang", "geo", "Xinjiang"),
    (r"tibet", "geo", "Tibet"),
    (r"inner mongolia", "geo", "Inner Mongolia"),
    (r"hong kong", "geo", "Hong Kong"),
    (r"macau", "geo", "Macau"),
    
    # Strategic Waterways
    (r"malacca strait", "geo", "Malacca Strait"),
    (r"strait of hormuz", "geo", "Strait of Hormuz"),
    (r"taiwan strait", "geo", "Taiwan Strait"),
    (r"luzon strait", "geo", "Luzon Strait"),
    (r"miyako strait", "geo", "Miyako Strait"),
    (r"tsushima strait", "geo", "Tsushima Strait"),
    (r"bashi channel", "geo", "Bashi Channel"),
    (r"pearl river delta", "geo", "Pearl River Delta"),
    (r"yangtze river delta", "geo", "Yangtze River Delta"),
    
    # Chinese Technology Companies
    (r"huawei", "actor", "Huawei"),
    (r"xiaomi", "actor", "Xiaomi"),
    (r"bytedance", "actor", "ByteDance"),
    (r"tencent", "actor", "Tencent"),
    (r"alibaba", "actor", "Alibaba"),
    (r"baidu", "actor", "Baidu"),
    (r"didi", "actor", "Didi Chuxing"),
    (r"meituan", "actor", "Meituan"),
    (r"pinduoduo", "actor", "Pinduoduo"),
    (r"zte", "actor", "ZTE"),
    (r"dji", "actor", "DJI"),
    (r"byd", "actor", "BYD"),
    (r"nio", "actor", "NIO"),
    (r"xpeng", "actor", "Xpeng"),
    (r"hikvision", "actor", "Hikvision"),
    (r"smic", "actor", "SMIC"),
    (r"boe technology", "actor", "BOE Technology"),
    
    # Chinese State-Owned Enterprises
    (r"china national offshore oil", "actor", "China National Offshore Oil Corporation"),
    (r"china petroleum", "actor", "China Petroleum & Chemical Corporation"),
    (r"state grid", "actor", "State Grid Corporation"),
    (r"china railway", "actor", "China Railway Group"),
    (r"china communications construction", "actor", "China Communications Construction"),
    (r"aviation industry corporation", "actor", "Aviation Industry Corporation of China"),
    (r"china shipbuilding", "actor", "China Shipbuilding Industry Corporation"),
    (r"china aerospace", "actor", "China Aerospace Science and Technology Corporation"),
    
    # Economic and Trade Events
    (r"economic (coercion|sanctions|pressure)", "security", "Economic Coercion"),
    (r"trade (war|dispute|conflict)", "event", "Trade War"),
    (r"technology (transfer|theft|espionage)", "event", "Technology Transfer"),
    (r"intellectual property (theft|violation)", "event", "Intellectual Property Theft"),
    (r"export (control|ban|restriction)", "policy", "Export Controls"),
    (r"import (ban|restriction|tariff)", "policy", "Import Restrictions"),
    (r"currency manipulation", "economy", "Currency Manipulation"),
    (r"trade deficit", "economy", "Trade Deficit"),
    (r"foreign investment", "economy", "Foreign Investment"),
    (r"supply chain", "economy", "Supply Chain"),
    (r"rare earth", "economy", "Rare Earth Elements"),
    (r"semiconductor", "economy", "Semiconductors"),
    (r"debt crisis", "economy", "Debt Crisis"),
    
    # Belt and Road Initiative
    (r"belt and road", "policy", "Belt and Road Initiative"),
    (r"one belt one road", "policy", "Belt and Road Initiative"),
    (r"obor", "policy", "Belt and Road Initiative"),
    (r"bri", "policy", "Belt and Road Initiative"),
    (r"silk road", "policy", "Belt and Road Initiative"),
    (r"maritime silk road", "policy", "Belt and Road Initiative"),
    (r"china-pakistan economic corridor", "policy", "Belt and Road Initiative"),
    (r"cpec", "policy", "Belt and Road Initiative"),
    
    # Military Capabilities
    (r"electronic warfare", "capability", "Electronic Warfare"),
    (r"radar (jamming|interference)", "capability", "Radar Jamming"),
    (r"hypersonic (missile|weapon)", "capability", "Hypersonic"),
    (r"anti-ship (missile|weapon)", "capability", "Anti-Ship Missile"),
    (r"air defense (system|missile)", "capability", "Air Defense"),
    (r"ballistic missile", "capability", "Ballistic Missile"),
    (r"cruise missile", "capability", "Cruise Missile"),
    (r"cyber (warfare|attack)", "capability", "Cyber Warfare"),
    (r"information warfare", "capability", "Information Warfare"),
    (r"cognitive warfare", "capability", "Cognitive Warfare"),
    (r"anti-access area denial", "capability", "Anti-Access Area Denial"),
    (r"a2/ad", "capability", "Anti-Access Area Denial"),
    (r"anti-satellite", "capability", "Anti-Satellite"),
    (r"asat", "capability", "Anti-Satellite"),
    (r"directed energy", "capability", "Directed Energy Weapons"),
    (r"laser weapon", "capability", "Laser Weapons"),
    (r"electromagnetic pulse", "capability", "Electromagnetic Pulse"),
    (r"emp", "capability", "Electromagnetic Pulse"),
    (r"quantum radar", "capability", "Quantum Radar"),
    (r"artificial intelligence warfare", "capability", "Artificial Intelligence Warfare"),
    (r"autonomous weapon", "capability", "Autonomous Weapons"),
    (r"drone swarm", "capability", "Drone Swarms"),
    (r"swarm technology", "capability", "Swarm Technology"),
    
    # Surveillance and Intelligence
    (r"surveillance (system|operation)", "security", "Surveillance"),
    (r"intelligence (gathering|collection)", "capability", "ISR"),
    (r"reconnaissance (mission|flight)", "capability", "ISR"),
    (r"spy (plane|aircraft|satellite)", "capability", "ISR"),
    (r"facial recognition", "security", "Surveillance"),
    (r"social credit", "society", "Social Credit System"),
    (r"mass surveillance", "security", "Surveillance"),
    (r"digital surveillance", "security", "Surveillance"),
    (r"ai surveillance", "technology", "AI Surveillance"),
    
    # Maritime Activities
    (r"exclusive economic zone", "geo", "Exclusive Economic Zone"),
    (r"nine-dash line", "geo", "Nine-Dash Line"),
    (r"maritime (rights|claims)", "policy", "Maritime Rights Protection"),
    (r"territorial (waters|sea)", "geo", "Territorial Waters"),
    (r"fishing (vessel|boat|fleet)", "actor", "Fishing Fleet"),
    (r"coast guard", "actor", "Coast Guard"),
    (r"scarborough shoal", "geo", "Scarborough Shoal"),
    (r"spratly islands", "geo", "Spratly Islands"),
    (r"paracel islands", "geo", "Paracel Islands"),
    (r"fiery cross reef", "geo", "Fiery Cross Reef"),
    (r"mischief reef", "geo", "Mischief Reef"),
    (r"subi reef", "geo", "Subi Reef"),
    (r"second thomas shoal", "geo", "Second Thomas Shoal"),
    (r"whitsun reef", "geo", "Whitsun Reef"),
    (r"reed bank", "geo", "Reed Bank"),
    
    # Political and Policy
    (r"one china policy", "policy", "One China Policy"),
    (r"made in china 2025", "policy", "Made in China 2025"),
    (r"dual circulation", "policy", "Dual Circulation"),
    (r"common prosperity", "policy", "Common Prosperity"),
    (r"zero covid", "policy", "Zero COVID"),
    (r"real estate crackdown", "policy", "Real Estate Crackdown"),
    (r"socialist market economy", "policy", "Socialist Market Economy"),
    (r"supply-side reform", "policy", "Supply-Side Structural Reform"),
    (r"new development paradigm", "policy", "New Development Paradigm"),
    (r"high-quality development", "policy", "High-Quality Development"),
    (r"innovation-driven development", "policy", "Innovation-Driven Development"),
    (r"rural revitalization", "policy", "Rural Revitalization"),
    (r"poverty alleviation", "policy", "Poverty Alleviation"),
    (r"targeted poverty", "policy", "Targeted Poverty Alleviation"),
    (r"state-owned enterprise reform", "policy", "State-Owned Enterprise Reform"),
    
    # Diplomatic Relations
    (r"wolf warrior (diplomacy|rhetoric)", "diplomacy", "Wolf Warrior Diplomacy"),
    (r"panda diplomacy", "diplomacy", "Panda Diplomacy"),
    (r"checkbook diplomacy", "diplomacy", "Checkbook Diplomacy"),
    (r"debt trap diplomacy", "diplomacy", "Debt Trap Diplomacy"),
    (r"soft power", "diplomacy", "Soft Power"),
    (r"hard power", "diplomacy", "Hard Power"),
    (r"sharp power", "diplomacy", "Sharp Power"),
    (r"great power diplomacy", "diplomacy", "Great Power Diplomacy"),
    (r"peripheral diplomacy", "diplomacy", "Peripheral Diplomacy"),
    (r"economic diplomacy", "diplomacy", "Economic Diplomacy"),
    (r"cultural diplomacy", "diplomacy", "Cultural Diplomacy"),
    (r"public diplomacy", "diplomacy", "Public Diplomacy"),
    (r"strategic partnership", "diplomacy", "Strategic Partnership"),
    (r"comprehensive partnership", "diplomacy", "Comprehensive Partnership"),
    (r"all-weather friendship", "diplomacy", "All-Weather Friendship"),
    (r"iron brotherhood", "diplomacy", "Iron Brotherhood"),
    (r"sino-us relations", "diplomacy", "Sino-US Relations"),
    (r"sino-russian relations", "diplomacy", "Sino-Russian Relations"),
    (r"sino-indian relations", "diplomacy", "Sino-Indian Relations"),
    (r"sino-japanese relations", "diplomacy", "Sino-Japanese Relations"),
    (r"cross-strait relations", "diplomacy", "Cross-Strait Relations"),
    
    # Technology and Innovation
    (r"artificial intelligence", "technology", "Artificial Intelligence"),
    (r"machine learning", "technology", "Machine Learning"),
    (r"quantum (computing|research)", "technology", "Quantum Research"),
    (r"5g (network|technology)", "technology", "5G"),
    (r"6g (network|technology)", "technology", "6G"),
    (r"big data", "technology", "Big Data"),
    (r"cloud computing", "technology", "Cloud Computing"),
    (r"blockchain", "technology", "Blockchain"),
    (r"cybersecurity", "technology", "Cybersecurity"),
    (r"space (technology|program)", "technology", "Space Technology"),
    (r"quantum supremacy", "technology", "Quantum Supremacy"),
    (r"quantum internet", "technology", "Quantum Internet"),
    (r"quantum sensors", "technology", "Quantum Sensors"),
    (r"quantum cryptography", "technology", "Quantum Cryptography"),
    (r"neural networks", "technology", "Neural Networks"),
    (r"deep learning", "technology", "Deep Learning"),
    (r"computer vision", "technology", "Computer Vision"),
    (r"natural language processing", "technology", "Natural Language Processing"),
    (r"robotics", "technology", "Robotics"),
    (r"automation", "technology", "Automation"),
    (r"smart manufacturing", "technology", "Smart Manufacturing"),
    (r"digital twins", "technology", "Digital Twins"),
    (r"augmented reality", "technology", "Augmented Reality"),
    (r"virtual reality", "technology", "Virtual Reality"),
    (r"gene editing", "technology", "Gene Editing"),
    (r"crispr", "technology", "CRISPR"),
    (r"synthetic biology", "technology", "Synthetic Biology"),
    (r"nanotechnology", "technology", "Nanotechnology"),
    (r"advanced materials", "technology", "Advanced Materials"),
    (r"superconductors", "technology", "Superconductors"),
    (r"fusion energy", "technology", "Fusion Energy"),
    (r"hydrogen energy", "technology", "Hydrogen Energy"),
    (r"carbon capture", "technology", "Carbon Capture"),
    (r"internet of things", "technology", "Internet of Things"),
    (r"edge computing", "technology", "Edge Computing"),
    (r"supercomputing", "technology", "Supercomputing"),
    (r"semiconductor manufacturing", "technology", "Semiconductor Manufacturing"),
    (r"chip design", "technology", "Chip Design"),
    
    # Space and Satellite Programs
    (r"tiangong", "platform", "Tiangong Space Station"),
    (r"shenzhou", "platform", "Shenzhou Spacecraft"),
    (r"tianwen", "platform", "Tianwen Mars Mission"),
    (r"chang'e", "platform", "Chang'e Lunar Program"),
    (r"beidou", "platform", "Beidou Navigation System"),
    (r"yaogan", "platform", "Yaogan Satellites"),
    (r"gaofen", "platform", "Gaofen Satellites"),
    (r"jilin-1", "platform", "Jilin-1 Constellation"),
    (r"kuaizhou", "platform", "Kuaizhou Rocket"),
    (r"long march", "platform", "Long March Rocket"),
    (r"changzheng", "platform", "Long March Rocket"),
    
    # Economic Terms
    (r"semiconductor (industry|chip)", "economy", "Semiconductors"),
    (r"gdp growth", "economy", "GDP Growth"),
    (r"inflation", "economy", "Inflation"),
    (r"unemployment", "economy", "Unemployment"),
    (r"chinese yuan", "economy", "Chinese Yuan"),
    (r"renminbi", "economy", "Renminbi"),
    (r"foreign exchange reserves", "economy", "Foreign Exchange Reserves"),
    (r"shanghai stock exchange", "economy", "Shanghai Stock Exchange"),
    (r"shenzhen stock exchange", "economy", "Shenzhen Stock Exchange"),
    (r"state-owned enterprises", "economy", "State-Owned Enterprises"),
    (r"private enterprises", "economy", "Private Enterprises"),
    (r"free trade zones", "economy", "Free Trade Zones"),
    (r"special economic zones", "economy", "Special Economic Zones"),
    
    # Legal and Regulatory
    (r"national security law", "law", "National Security Law"),
    (r"data privacy law", "law", "Data Privacy Law"),
    (r"cybersecurity law", "law", "Cybersecurity Law"),
    (r"foreign investment law", "law", "Foreign Investment Law"),
    (r"export control law", "law", "Export Control Law"),
    (r"anti-foreign sanctions law", "law", "Anti-Foreign Sanctions Law"),
    (r"personal information protection law", "law", "Personal Information Protection Law"),
    (r"data security law", "law", "Data Security Law"),
    (r"e-commerce law", "law", "E-Commerce Law"),
    (r"cryptography law", "law", "Cryptography Law"),
    (r"network security law", "law", "Network Security Law"),
    (r"counter-terrorism law", "law", "Counter-Terrorism Law"),
    (r"counter-espionage law", "law", "Counter-Espionage Law"),
    (r"state secrets law", "law", "State Secrets Law"),
    (r"unclos", "law", "UNCLOS"),
    (r"maritime law", "law", "Maritime Law"),
    (r"trade law", "law", "Trade Law"),
    
    # Social and Ideological
    (r"social credit system", "society", "Social Credit System"),
    (r"patriotic education", "ideology", "Patriotic Education"),
    (r"xi thought", "ideology", "Xi Thought"),
    (r"xi jinping thought", "ideology", "Xi Jinping Thought"),
    (r"socialism with chinese characteristics", "ideology", "Socialism with Chinese Characteristics"),
    (r"chinese dream", "ideology", "Chinese Dream"),
    (r"four comprehensives", "ideology", "Four Comprehensives"),
    (r"five-in-one layout", "ideology", "Five-in-One Layout"),
    (r"two establishes", "ideology", "Two Establishes"),
    (r"two upholds", "ideology", "Two Upholds"),
    (r"party leadership", "ideology", "Party Leadership"),
    (r"democratic centralism", "ideology", "Democratic Centralism"),
    (r"mass line", "ideology", "Mass Line"),
    (r"seek truth from facts", "ideology", "Seek Truth from Facts"),
    (r"reform and opening up", "ideology", "Reform and Opening Up"),
    (r"youth unemployment", "society", "Youth Unemployment"),
    (r"covid-19 lockdown", "society", "COVID-19 Lockdown"),
    (r"censorship", "society", "Censorship"),
    (r"human rights", "society", "Human Rights"),
    (r"democracy", "society", "Democracy"),
    (r"authoritarianism", "society", "Authoritarianism"),
    (r"nationalism", "society", "Nationalism"),
    (r"patriotism", "society", "Patriotism"),
    (r"aging population", "society", "Aging Population"),
    (r"one-child policy", "society", "One-Child Policy"),
    (r"three-child policy", "society", "Three-Child Policy"),
    (r"birth rate decline", "society", "Birth Rate Decline"),
    (r"urban-rural divide", "society", "Urban-Rural Divide"),
    (r"income inequality", "society", "Income Inequality"),
    (r"wealth gap", "society", "Wealth Gap"),
    (r"migrant workers", "society", "Migrant Workers"),
    (r"hukou system", "society", "Hukou System"),
    (r"women's rights", "society", "Women's Rights"),
    (r"environmental activism", "society", "Environmental Activism"),
    (r"student activism", "society", "Student Activism"),
    (r"civil society", "society", "Civil Society"),
    (r"online activism", "society", "Online Activism"),
    (r"digital resistance", "society", "Digital Resistance"),
    (r"confucianism", "society", "Confucianism"),
    (r"buddhism", "society", "Buddhism"),
    (r"taoism", "society", "Taoism"),
    (r"cultural revolution", "society", "Cultural Revolution"),
    (r"traditional culture", "society", "Traditional Culture"),
    (r"digital divide", "society", "Digital Divide"),
    (r"internet addiction", "society", "Internet Addiction"),
    (r"mobile payments", "technology", "Mobile Payments"),
    (r"digital currency", "economy", "Digital Currency"),
    (r"privacy rights", "society", "Privacy Rights"),
    (r"data protection", "society", "Data Protection"),
    
    # International Organizations
    (r"shanghai cooperation organization", "actor", "Shanghai Cooperation Organization"),
    (r"sco", "actor", "Shanghai Cooperation Organization"),
    (r"brics", "actor", "BRICS"),
    (r"asian infrastructure investment bank", "actor", "Asian Infrastructure Investment Bank"),
    (r"aiib", "actor", "Asian Infrastructure Investment Bank"),
    (r"new development bank", "actor", "New Development Bank"),
    (r"silk road fund", "actor", "Silk Road Fund"),
    (r"china-africa development fund", "actor", "China-Africa Development Fund"),
    (r"regional comprehensive economic partnership", "actor", "Regional Comprehensive Economic Partnership"),
    (r"rcep", "actor", "Regional Comprehensive Economic Partnership"),
    
    # Security Threats and Concepts
    (r"three evil forces", "security", "Three Evil Forces"),
    (r"terrorism", "security", "Terrorism"),
    (r"separatism", "security", "Separatism"),
    (r"extremism", "security", "Extremism"),
    (r"color revolution", "security", "Color Revolution"),
    (r"peaceful evolution", "security", "Peaceful Evolution"),
    (r"foreign interference", "security", "Foreign Interference"),
    (r"subversion", "security", "Subversion"),
    (r"infiltration", "security", "Infiltration"),
    (r"espionage", "security", "Espionage"),
    (r"sabotage", "security", "Sabotage"),
    (r"cyber espionage", "security", "Cyber Espionage"),
    (r"cyber terrorism", "security", "Cyber Terrorism"),
    (r"cyber crime", "security", "Cyber Crime"),
    (r"data breach", "security", "Data Breach"),
    (r"network attack", "security", "Network Attack"),
    (r"malware", "security", "Malware"),
    (r"ransomware", "security", "Ransomware"),
    (r"phishing", "security", "Phishing"),
    (r"advanced persistent threat", "security", "Advanced Persistent Threat"),
    (r"zero-day exploit", "security", "Zero-Day Exploit"),
    (r"comprehensive national security", "security", "Comprehensive National Security"),
    (r"traditional security", "security", "Traditional Security"),
    (r"non-traditional security", "security", "Non-Traditional Security"),
    (r"energy security", "security", "Energy Security"),
    (r"food security", "security", "Food Security"),
    (r"water security", "security", "Water Security"),
    (r"supply chain security", "security", "Supply Chain Security"),
    (r"critical infrastructure protection", "security", "Critical Infrastructure Protection"),
    (r"financial security", "security", "Financial Security"),
    (r"trade security", "security", "Trade Security"),
    (r"investment security", "security", "Investment Security"),
    (r"technology security", "security", "Technology Security"),
    (r"innovation security", "security", "Innovation Security"),
    
    # Ethnic and Regional Issues
    (r"uyghur", "society", "Uyghur"),
    (r"tibetan", "society", "Tibet"),
    (r"ethnic unity", "policy", "Ethnic Unity"),
    (r"religious harmony", "policy", "Religious Harmony"),
    (r"sinicization", "policy", "Sinicization of Religion"),
    (r"cultural preservation", "policy", "Cultural Preservation"),
    (r"language policy", "policy", "Language Policy"),
    
    # Historical References
    (r"mao zedong", "command", "Mao Zedong"),
    (r"deng xiaoping", "command", "Deng Xiaoping"),
    (r"jiang zemin", "command", "Jiang Zemin"),
    (r"hu jintao", "command", "Hu Jintao"),
    (r"zhou enlai", "command", "Zhou Enlai"),
    (r"liu shaoqi", "command", "Liu Shaoqi"),
    (r"zhu de", "command", "Zhu De"),
    (r"chen yun", "command", "Chen Yun"),
    (r"li peng", "command", "Li Peng"),
    (r"zhu rongji", "command", "Zhu Rongji"),
    (r"wen jiabao", "command", "Wen Jiabao"),
    (r"hu yaobang", "command", "Hu Yaobang"),
    (r"zhao ziyang", "command", "Zhao Ziyang"),
    (r"mao zedong thought", "ideology", "Mao Zedong Thought"),
    (r"deng xiaoping theory", "ideology", "Deng Xiaoping Theory"),
    (r"three represents", "ideology", "Three Represents"),
    (r"scientific development", "ideology", "Scientific Development"),
    (r"marxism-leninism", "ideology", "Marxism-Leninism"),
    
    # Military Doctrines and Strategies
    (r"active defense", "policy", "Active Defense"),
    (r"military-civil fusion", "policy", "Military-Civil Fusion"),
    (r"strong army strategy", "policy", "Strong Army Strategy"),
    (r"joint operations", "policy", "Joint Operations"),
    (r"informatization", "policy", "Informatization"),
    (r"intelligentization", "policy", "Intelligentization"),
    (r"military modernization", "policy", "Military Modernization"),
    (r"nuclear no-first-use", "policy", "Nuclear No-First-Use"),
    (r"defensive nuclear strategy", "policy", "Defensive Nuclear Strategy"),
    (r"peace through strength", "policy", "Peace Through Strength"),
    
    # Foreign Policy Concepts
    (r"peaceful development", "policy", "Peaceful Development"),
    (r"win-win cooperation", "policy", "Win-Win Cooperation"),
    (r"community of shared future", "policy", "Community of Shared Future"),
    (r"new type of great power relations", "policy", "New Type of Great Power Relations"),
    (r"five principles of peaceful coexistence", "policy", "Five Principles of Peaceful Coexistence"),
    (r"good neighborly relations", "policy", "Good Neighborly Relations"),
    (r"non-interference", "policy", "Non-Interference Policy"),
    (r"south-south cooperation", "policy", "South-South Cooperation"),
    (r"multilateralism", "policy", "Multilateralism"),
    (r"global governance reform", "policy", "Global Governance Reform"),
    (r"international law adherence", "policy", "International Law Adherence"),
    
    # Technology Innovation Policies
    (r"independent innovation", "policy", "Independent Innovation"),
    (r"indigenous innovation", "policy", "Indigenous Innovation"),
    (r"technological self-reliance", "policy", "Technological Self-Reliance"),
    (r"digital economy development", "policy", "Digital Economy Development"),
    (r"internet plus", "policy", "Internet Plus"),
    (r"mass entrepreneurship", "policy", "Mass Entrepreneurship and Innovation"),
    (r"talent development strategy", "policy", "Talent Development Strategy"),
    (r"scientific development concept", "policy", "Scientific Development Concept"),
    (r"technology transfer regulation", "policy", "Technology Transfer Regulation")
] 